### PR TITLE
fix for placeholder

### PR DESCRIPTION
**Pull request by aloncarmel**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper-1** [comment]
Thanks aloncarmel, I'll review the changes right away!

**Comment by aloncarmel** [comment]
Screen Shot 2022-12-10 at 1 39 37

**Review by vanessa-cooper-1 — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper-1 — APPROVED** [review]
Excellent job aloncarmel! You're now able to merge the PR.

**Pull request merged**
